#include "Shader.h"

#include "HelloTriangle.vert"
#include "HelloTriangle.frag"
#include "GeometryShader.vert"
#include "GeometryShader.frag"
#include "GeometryShader.geom"
#include "GeometryShaderExplode.vert"
#include "GeometryShaderExplode.frag"
#include "GeometryShaderExplode.geom"
#include "GeometryShaderNormal.vert"
#include "GeometryShaderNormal.frag"
#include "GeometryShaderNormal.geom"
#include "GeometryShaderModel.vert"
#include "GeometryShaderModel.frag"